# books
mutation CreateBook($name: String!) @auth(level: USER_EMAIL_VERIFIED) {
  book_insert(data: { name: $name })
}

mutation UpdateBook(
  $id: UUID!
  $name: String!
  $price: Int
  $imagePath: String
  $writtenBy: String
  $illustratedBy: String
  $publisher: String
) @auth(level: USER) {
  book_update(
    data: {
      name: $name
      price: $price
      imagePath: $imagePath
      writtenBy: $writtenBy
      illustratedBy: $illustratedBy
      publisher: $publisher
    }
    key: { id: $id }
  )
}

mutation DeleteBook($id: UUID!) @auth(level: USER) {
  book_delete(key: { id: $id })
}

# stockLogs
mutation CreateStockLog($bookId: UUID!, $date: Date!, $quantity: Int!, $memo: String) @auth(level: USER) {
  stockLog_insert(data: { book: { id: $bookId }, date: $date, quantity: $quantity, memo: $memo })
}
