
# books
query ListBooks @auth(level: PUBLIC) {
  books {
    id
    name
    price
    imagePath
    writtenBy
    illustratedBy
    publisher
  }
}

query GetBookById($id: UUID!) @auth(level: PUBLIC) {
  book(id: $id) {
    id
    name
    price
    imagePath
    writtenBy
    illustratedBy
    publisher
  }
}

# stockLogs
query ListStockLogs @auth(level: USER) {
  stockLogs {
    id
    book {
      id
      name
    }
    date
    quantity
    memo
    createdAt
  }
}
